name: Lambda layer for python
author: Lukáš Orčík
description: Deploy python code to AWS Lambda with dependencies in a separate layer.
inputs:
  requirements_txt:
    description: the name/path to the requirements.txt file
    required: true
    default: 'requirements.txt'
  lambda_layer_arn:
    description: The ARN for the Lambda layer the dependencies (every push is a new version).
    required: true
  architectures:
    description: Target architectures
    required: false
    default: 'x86_64'
  runtimes:
    description: Compatible runtimes in space-separated string
    required: false
    default: 'python3.9 python3.8'
  package_path:
    description: Package path
    required: true
    default: 'common'
  layer_description:
    description: Layer description
    required: false
    default: 'verion 0.1.17'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.requirements_txt }}
    - ${{ inputs.lambda_layer_arn }}
    - ${{ inputs.architectures }}
    - ${{ inputs.runtimes }}
    - ${{ inputs.package_path }}
    - ${{ inputs.layer_description }}
branding:
  icon: 'layers'
  color: 'blue'